  name: Windows Build

  on:
    push:
      branches:
        - main
    workflow_dispatch:

  jobs:
    build-windows:
      runs-on: windows-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install Qt
          uses: jurplel/install-qt-action@v4
          with:
            version: '6.8.3'
            host: windows
            target: desktop
            arch: win64_msvc2022_64
            modules: 'qtshadertools'

        - name: Configure CMake
          run: cmake -B build -S . -G "Visual Studio 17 2022" -A x64

        - name: Build
          run: cmake --build build --config Release

        - name: Deploy Qt
          shell: pwsh
          run: |
            mkdir release
            Copy-Item "build/Release/Qt6QmlApp.exe" "release/"
            
            windeployqt `
              --release `
              --qmldir . `
              "release/Qt6QmlApp.exe"

        - name: Upload Windows application
          uses: actions/upload-artifact@v4
          with:
            name: Qt6QmlApp-Windows
            path: release/
